# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Saedal.SaedalBrowser
PackageVersion: 0.4.4
InstallerLocale: ko-KR
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ReleaseDate: 2026-09-29
AppsAndFeaturesEntries:
- DisplayName: Saedal Browser
Installers:
- Architecture: x64
  InstallerUrl: https://saedal.com/browser/releases/Saedal%20Browser%20Setup%200.4.4.exe
  InstallerSha256: 984E445BFC40CD9B9235F55DFBF0F374519108D784EA401FA9C9DB468448D04F
ManifestType: installer
ManifestVersion: 1.9.0
