# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.9.0.schema.json

PackageIdentifier: Saedal.SaedalBrowser
PackageVersion: 0.4.4
PackageLocale: ko-KR
Publisher: Saedal
PackageName: Saedal Browser
License: 프리웨어
ShortDescription: Saedal 계정 동기화, Chrome 확장 프로그램, 자동 보안 업데이트를 지원하는 Chromium 기반 웹 브라우저
Tags:
- 브라우저
- 웹브라우저
ManifestType: locale
ManifestVersion: 1.9.0
