# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Saedal.SaedalBrowser
PackageVersion: 0.4.3
PackageLocale: en-US
Publisher: Saedal Inc.
PublisherUrl: https://saedal.com/
PackageName: Saedal Browser
PackageUrl: https://saedal.com/browser/
License: Freeware
Copyright: Copyright (c) Saedal Inc.
ShortDescription: Chromium-based web browser with Saedal account sync, Chrome extension support and automatic security updates.
Moniker: saedal
Tags:
- browser
- chromium
- web-browser
ManifestType: defaultLocale
ManifestVersion: 1.9.0
